
/** 标题注释区
@startuml
scale 1920*1080
'配置区


' 顶部
' header 食途科技
'title 动态
'主体区
(*)--> 点击进入小程序or网页端
-> 一键微信登录or用户名密码登录
-> 系统进行登录鉴权
--> 进入应用首页
-left> 点击问卷查看详细
-left> 点击开始填写问卷
-left> 提交问卷
-->(*)


'尾部
'caption
'说明:
'动态模块业务流程

'end caption


'样式区
<style>

caption{
FontColor Black
}
header{
FontColor Black
FontSize 18
}
</style>

@enduml




/** 标题注释区
@startuml
scale 1920*1080
'配置区


' 顶部
' header 食途科技
'title 动态
'主体区
(*)-->点击进入小程序
-> 一键微信登录
-> 系统进行登录鉴权
-> 进入动态首页
--> 点击动态查看详细
if 点击点赞
    -> 系统结合redis缓存更新数据
else
if 点击发布动态
    -> 进入动态编辑页面
    -> 点击上传图片
    -> 选择图片
    if 点击发布
       -> [成功]返回动态页面
       --> (*)
    else
       -> [失败]返回动态编辑页面
    endif
else
if 点击评论动态
    --> 弹出评论编辑框
    --> 点击发布评论
    --> (*)
else
if 点击评论评论
    --> 弹出评论编辑框
endif


'尾部
'caption
'说明:
'动态模块业务流程

'end caption


'样式区
<style>

caption{
FontColor Black
}
header{
FontColor Black
FontSize 18
}
</style>

@enduml



