@startuml
小程序 -> 小程序:获取session_code
小程序 -> 后端:携带code登录
后端 -> 微信服务器:携带code/appid登录
微信服务器 --> 后端:openid session_key
后端 -> 数据库:获取用户信息
数据库 -> 后端: 放回用户信息
后端 --> 小程序:返回登录信息
小程序->小程序: 重新微信登录获取code
小程序 -> 后端: 携带code注册
后端 -> 微信服务器:携带code登录
微信服务器 --> 后端:openid session_key
后端 -> 数据库:校验openid注册
后端 -->小程序:分发token
@enduml